n10817468 IAB207 Demo/travel/models.py
class Destination:

    def __init__(self, name, description, image, currency):
        self.name = name
        self.description = description
        self.image = image
        self.currency = currency
        self.comments = list()

    def set_comments(self, comment):
        self.comments.append(comment)

    def __repr__(self):
        return f"Name: {self.name}, Currency: {self.currency}"

class Comment:
    def __init__(self,user, text, created_at):
        self.user = user
        self.text = text
        self.created_at = created_at

    def __repr__(self):
        return f"User {self.user}, \n Text {self.text}"

n10817468 IAB207 Demo/travel/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField, SubmitField, StringField, PasswordField
from wtforms.validators import InputRequired, Email, EqualTo

#Create new destination
class DestinationForm(FlaskForm):
  name = StringField('Country', validators=[InputRequired()])
  description = TextAreaField('Description', 
            validators = [InputRequired()])
  image = StringField('Cover Image', validators=[InputRequired()])
  currency = StringField('Currency', validators=[InputRequired()])
  submit = SubmitField("Create")
    
#User login
class LoginForm(FlaskForm):
    user_name = StringField("User Name", validators=[InputRequired('Enter user name')])
    password = PasswordField("Password", validators=[InputRequired('Enter user password')])
    submit = SubmitField("Login")

#User register
class RegisterForm(FlaskForm):
    user_name = StringField("User Name", validators=[InputRequired()])
    email_id = StringField("Email Address", validators=[Email("Please enter a valid email")])
    
    #linking two fields - password should be equal to data entered in confirm
    password = PasswordField("Password", validators=[InputRequired(),
                  EqualTo('confirm', message="Passwords should match")])
    confirm = PasswordField("Confirm Password")
    #submit button
    submit = SubmitField("Register")

#User comment
class CommentForm(FlaskForm):
  text = TextAreaField('Comment', [InputRequired()])
  submit = SubmitField('Create')

n10817468 IAB207 Demo/travel/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5

def create_app():
    app = Flask(__name__)

    #we use this utility module to display forms quickly
    Bootstrap5(app)

    #A secret key for the session object
    app.secret_key = 'somerandomvalue'
    
    #add Blueprints
    from . import views
    app.register_blueprint(views.mainbp)
    from . import destinations
    app.register_blueprint(destinations.destbp)
    from . import auth
    app.register_blueprint(auth.authbp)

    return app

n10817468 IAB207 Demo/travel/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm

#create a blueprint
authbp = Blueprint('auth', __name__ )

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    loginForm = LoginForm()
    if loginForm.validate_on_submit():
        print('Successfully logged in')
        flash('You logged in successfully')
        return redirect(url_for('auth.login'))
    return render_template('user.html', form=loginForm,  heading='Login')

@authbp.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        print('Successfully registered')
        return redirect(url_for('auth.login'))
    return render_template('user.html', form=form)

n10817468 IAB207 Demo/travel/views.py
from flask import Blueprint, render_template

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    return render_template('index.html')

n10817468 IAB207 Demo/travel/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>My Travel App</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

</head>

<body>
    <!-- Header -->
    <header class="bg-dark border-bottom">

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-caution">
            <div class="container">

                <!-- Your Travel App Name or Logo -->
                <a href="/" class="navbar-brand">My Travel App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="#">Destinations</a>
                        <a class="nav-item nav-link" href="#">Bookings</a>
                    </div>
                </div>
            </div>
        </nav>

        {% block header %}
        {% endblock %}

    </header>

        {% block content %}
        {% endblock %}

    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; 2024</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

</html>

n10817468 IAB207 Demo/travel/templates/destinations/create.html
{% extends 'base.html' %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-12">
            <h1>Add Travel Destination</h1>
            <p>Enter a country that you will help clients travel to.</p>
            {{render_form(form)}}
        </div>
    </div>
</div>

{% endblock %}

n10817468 IAB207 Demo/travel/templates/destinations/show.html
{% extends 'base.html' %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container">
    <div class="row mt-5 mb-3">
        <div class="col-md-12">
            <div class="float-left">
                <h1 class="mb-0">{{destination.name}}</h1>
                <p>Popular Destination</p>
            </div>

            <div class="float-right text-right">
                <p class="mb-0">1 AUD equals</p>
                <h2 id="exchange-rate">0.62 {{destination.currency}}</h1>
            </div>
        </div>
    </div>

    <!-- Destination -->
    <div class="row">
        <div class="col-md-12">
            <div class="card my-3">
                <div class="card-body">
                    <div class="media">
                        <img class="align-self-start mr-3" src="{{destination.image}}">
                        <div class="media-body">
                            <small class="font-weight-bold text-muted">Stay 2 nights</small>
                            <h5 class="mt-0">{{destination.name}}</h5>
                            <p>{{destination.description}}</p>
                            <a href="#" class="btn btn-danger">Book Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <!-- Comments -->
    <div class="row">
        <div class="col-md-12">
            <h2>Comments</h1>
        </div>
    </div>

    <div class="row border-bottom">
        {{render_form(form,"/destinations/{0}/comment".format(1))}}
        {% for comment in destination.comments %}
        <div class="col-md-12">
            <b>{{comment.user}} <span class="ml-2 text-muted">January 2024</span></b>
            <p>{{comment.text}}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

n10817468 IAB207 Demo/travel/templates/index.html
{% extends 'base.html' %}

{% block header %}
<!--Jumbotron-->
<div class="container">
    <div class="row justify-content-center mt-5 pb-4">
        <div class="col-md-8">
            <div class="card shadow p-5 mb-5 bg-light">
                <h1 class="text-center mb-3">Find our best travel deals</h1>
                <form class="form-inline d-flex flex-nowrap">

                    <select class="form-select" aria-label="Default select example">
                        <option selected>Select a destination...</option>
                        <option value="america">America</option>
                        <option value="africa">Africa</option>
                    </select>
                    <button type="submit" class="flex-shrink-1 btn btn-primary ms-2">Submit</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5 mb-5 justify-content-center">
        <div class="col-md-10">
            <div class="media border p-3 d-flex justify-content-start">
                <img class="align-self-center me-3" style="max-width:120px"
                     src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png"
                     alt="Planet Earth">
                <div class="align-self-center media-body">
                    <h5 class="mt-0">Find the best destinations on earth</h5>
                    <p class="d-none d-sm-block">
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                        scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra
                        turpis. Fusce condimentum nunc ac nisi vulputate fringilla.
                    </p>
                    <a href="#" class="btn btn-primary">Join Now</a>
                </div>
            </div>
        </div>
    </div>

    <div class="card-group">
        <div class="card mx-3">
            <img class="card-img-top"
                 src="https://media-cdn.tripadvisor.com/media/photo-s/0e/9c/a0/02/eiffel-tower.jpg" alt="France">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">
                    This card has supporting text below as a natural lead-in to additional content.
                </p>
            </div>
            <div class="card-footer"><small class="text-muted">Last updated 3 mins ago</small></div>
        </div>
        <div class="card mx-3">
            <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/12/44/87/23/london.jpg"
                 alt="United Kingdom">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">
                    This card has supporting text below as a natural lead-in to additional content.
                </p>
            </div>
            <div class="card-footer"><small class="text-muted">Last updated 3 mins ago</small></div>
        </div>
        <div class="card mx-3">
            <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/12/44/6e/a0/rome.jpg"
                 alt="Italy">
            <div class="card-body">
                <h5 class="card-title">Nice place</h5>
                <p class="card-text">
                    This card has supporting text below as a natural lead-in to additional content.
                </p>
            </div>
            <div class="card-footer"><small class="text-muted">Last updated 3 mins ago</small></div>
        </div>
    </div>
</div>
{% endblock %}

n10817468 IAB207 Demo/travel/templates/user.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container-fluid">
    <div class="page-header">
        <h4>{{heading}}</h4>
    </div>

    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %}
    {% if messages %} <!-- check if there are any messages -->
    <div class="container-fluid">
        <div class="row mt-3 mb-3">
            <div class="col-md-12">
                {% for message in messages %} <!--loop through the messages-->
                <div class="alert alert-info">{{message}}</div> <!--display as alert-->
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="col-md-6 ml-5">
        {{render_form(form)}}
    </div>

    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower == 'login' %}
    <div class="col-md-4 mb-5 ml-5">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}
</div>
{% endblock %}